
version: '3.9'

services:

    jupyter:
        build: .
        image: stable-diffusion
        ports:
            - 8988:80
        volumes:
            - ./project:/project
        command: jupyter lab --ip=0.0.0.0 --port=8988 --allow-root
        deploy:
            resources:
                reservations:
                    devices:
                    - capabilities: [gpu]
